spring:
  application:
    name: eureka-client
eureka:
#  instance:
#    appname: eureka-client
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/